name: Docs

on:
  push:
    branches: [ master ]
    paths:
      - docs
  pull_request:
    branches: [ master ]
    paths:
      - docs

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install APT dependencies
      run: |
        sudo apt-get install -y git build-essential apt-utils wget libfreetype6 libpng-dev libopenblas-dev gcc gfortran libsnappy-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry install --with docs

    - name: Build docs
      run: |
        poetry run make docs

    - name: Push to gh-pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
